# Generated by Django 3.2 on 2021-12-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
        ),
        migrations.AddField(
            model_name='inflow',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outflow',
            name='repetition_interval',
            field=models.PositiveSmallIntegerField(choices=[(1, 'N/A'), (2, 'DAYS'), (3, 'WEEKS'), (4, 'MONTHS'), (5, 'YEARS')], default=1),
        ),
        migrations.AddField(
            model_name='outflow',
            name='repetition_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SALES'), (2, 'DIVIDEND'), (3, 'INTEREST'), (4, 'RETURN'), (5, 'OTHER')]),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EXPENSES'), (2, 'COST OF REVENUE'), (3, 'SALARIES'), (4, 'RENT'), (5, 'OTHER')]),
        ),
    ]
